services:
  postgres:
    image: postgres:16
    container_name: gameadmin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gameadmin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: gameadmin-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: gameadmin-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: [ "start-dev" ]
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gameadmin-app
    restart: unless-stopped
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/gameadmin
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWK_SET_URI: http://keycloak:8080/realms/gameadmin-realm/protocol/openid-connect/certs
      ISSUER_URI: ${ISSUER_URI}
    depends_on:
      - postgres
      - keycloak
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  keycloak_data:
  pgadmin_data: