spring:
  application:
    name: gameadmin

  datasource:
    url: jdbc:postgresql://localhost:5432/gameadmin
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
